Changelog = {}

Changelog['v0.1'] = [[
Added commands: echo, hello, info, help, changelog, kiss, boop, hug, slap
]]

Changelog['v0.2'] = [[
Added Commands:
roll, flip

Fixed issues:
- Bot crash when hugging/slapping/kissing/booping/patting yourself in dms of the bot
- Bot crash when rolling die with one argument and no seperator
- Added pat command

Other:
- Commands are now caseinsensitive
- Prefixes can now be multiple strings long
- Added auto "git pull" request in start.sh script for automatic updates
]]

Changelog['v0.3'] = [[
Added command:
- convert (converts units of measurements)
]]

Changelog['v0.4'] = [[
Added commands:
- pickrandom (picks a random word from supplied arguments, split by spaces)
- ynm (ask a question and get a reply ranging from yes, no or maybe)
- checklove (ping two users and get their love value calculated based on their discord IDs)
- checktruth (provide a string of text after the command name and get the string's objective, inrefutable and correct truth value)

Changes:
- Help command is now more compact
- added a "Playing" status message
]]

Changelog['v0.4.1'] = [[
Changes:
- convert command now only displays list of units when executing `convert list`, not cluttering up your full screen :)
- more units added to the convert command
- info command with more information

Fixed Issues:
- Bot crash when executing checklove command with the same person as both arguments
- convert command value correction
- spelling mistakes

Added Functionality:
- Bot can now run shell scripts through commands, giving more interaction with the host system
]]

Changelog['v1.0.0'] = [[
Changes:
- Commands have been migrated to be sent as embeds
]]

Changelog['v1.1.0'] = [[
Added Commands:
- profile (display a users server profile)
]]

Changelog['v1.2.0'] = [[
Added Commands:
- date (date @AnotherUser, to date them with an autogenerated date prompt)

Added Functionality:
- Bot can now listen and respond to reactions by users on specific messages (very big)
]]

Changelog['v1.3.0'] = [[
Added Commands:
- rps (Rock paper scissors, utilising reactions to a bot message)

Added Functionality:
- Commands now have the capablility to have aliases (for example: 'info' and 'botinfo' both execute the info-command)
]]

Changelog['v1.3.1'] = [[
Fixed Issues:
- Gifs not displayed with social commands

Other:
- a lot more gifs, including some cat gifs -v-
- removed required ID, automated through Discord API (api token magic)
]]

Changelog['v1.3.2'] = [[
Added Commands:
- neofetch (warning: nerd alert!)
- settings (not yet working, WIP)

Other:
- organised file structure
]]

Changelog['v1.3.3'] = [[
Added Functionality:
- Goodies (gain goodies by talking to people on discord servers, which will be later used in some commands)

Other:
- organised file structure again :)
]]

return Changelog
